language: go

matrix:
  include:
    - go: 1.10.x
      install:
        - go get github.com/ugorji/go/codec
        - go get github.com/pquerna/ffjson/fflib/v1
        - go get github.com/json-iterator/go
        - go get golang.org/x/lint/golint
    - go: 1.11.x
    - go: tip

env:
  - GO111MODULE=on

script:
  - make